### ISSUE TITLE
Keep getting Promoted

### ISSUE THREAD

**Issue by KoetseJ** [Staartvin/Autorank-2#24]
Hi,

Everything works but for some reason all my players who passed the 1 hour mark keep getting the message that they are promoted every min or so.

this is my config:

```
ranks:
    Newbie:
        requirements:
            time:
                value: 1h
        results:
            rank change: Newbie;Irregular
            message: 'Congratulations, you are now a Irregular. After 7 Days you will be promoted to Regular.'
            command: 'broadcast &p played for 1 Hour and is now an Irregular!'
    Irregular:
        requirements:
            time:
                value: 7d
        results:
            rank change: Irregular;Regular
            message: 'Congratulations, you are now a Regular.'
            command: 'broadcast &p played for 1 Week and is now an Regular!'
```

I'm using Zpermissions as permissions manager.

Do you know how to fix it?

Regards Jurre

**Comment by HighTide** [comment]
I'll tell you how I fixed it. The problem is not in vault and partially in this plugin. It can be easily fixed by going to the zperm config. Somewhere at the bottom there is a potion to only return 1 group. Instead of all the groups, you inherit. You need to turn that off. (can't remember the name)

What happens is the following: you have the ranks guest, player, long-player.
Long player inherits from player, player from guest. With that option on if you are in old player zperm will say: player xxx is in group guest, player and old player.

This plugin keeps thinking it needs to promote you cause it still checks if you're in the group guest.

Sorry, I posted from my phone.

**Comment by MedicinalSnacks** [comment]
Same problem with PEX.

**Comment by MedicinalSnacks** [comment]
AutoRank is seemingly giving away a rank every time the plugin checks for time played (I have it set to 5 minutes).
