### ISSUE TITLE
AFK integration time not working?

### ISSUE THREAD

**Issue by groovyloopylou** [Staartvin/Autorank-2#427]
Using latest version (Autorank-3.8.5.1.jar) and Spigot 1.11

Players are still getting time added even when afk
in Setting.yml
afk integration: true

Using essentials. Our money over time plugin is behaving correctly with being marked afk so I'm assuming essentials isn't the problem.

**Comment by Staartvin** [comment]
I will look into this.

**Comment by EnderSandman** [comment]
I am having the same issue.  I am using EssentialsX, Autorank-3.8.5.1.jar, Spigot 1.11.2. AFK time is counted at playing time with both Autorank and Statz. Thanks for looking into this.

groovylooplou,
If it helps you until this issue is fixed, I set the following in my Essentials config.yml file so players are kicked as soon as they go AFK:

auto-afk: 300
auto-afk-kick: 300

**Comment by Sidious82** [comment]
ditto
