### ISSUE TITLE
Custom Recent time options?

### ISSUE THREAD

**Issue by shauncoyne** [Staartvin/Autorank-2#446]
I would to make ranks like this:

Hobo-default
Peasant- has mined within the last two days
FarmerBrown- has fished, mined, hunted, and farmed within the last two days
Dedicated- has done x,y,z,q,e,t,h,d,q,g, and b things in the last two days.

Then i would set the ranks to be derankable and if they become inactive they loose the rank.

**Comment by Proplex** [comment]
To add to this, it would be really nice if we could have a general "weekly time" value. There's total server/network time, but the ability to break it down by week would be nice (i.e. to judge how active a player is over a period of time rather than just total time since their join)

**Comment by mickcoyne** [comment]
Really, if it kept track of activity day by day (like how many hours in day one since joining, how many hours on day 2, how many hours on day 3...) Then add a feature to review this data in increments as small as one day and then say weekly averages, then monthly averages we could see all kinds of data. /ar timequerry [user]  [interval]. (this is kinda what you want right Proplex?)

More importantly, this would also allow easier implementation of my feature request being that in the config I set "activity requirement" amount: 10 (this being hours) increment: 3 (this being days) Then I set this to be derankable. I have now created a rank that you can only keep if you play 10 hours over 3 days.  

So you and I have different ideas @Proplex however I think they would go well together in the next update so long as @Armarr is inspired to do so!

**Comment by Staartvin** [comment]
@Staartvin reporting in, it's certainly possible. However, it will require me to rewrite quite a few things. I would love to add these features, but I feel like this might get too complex for the _average_ user. Is there a way that this could be implemented so that average users don't feel overwhelmed by this 'complexity'?

**Comment by mickcoyne** [comment]
I think the easiest way of viewing the information player side would be a command to see each individual player's activity. Example as follows (I dragged out the example to be clear)

player: /ar activity 
result: usage is /ar activity [username] [interval]

player: /ar activity Staartvin
result: requires interval: "day" "week" "month" "year"

player: /ar activity Staartvin day
result:
 2/1/2017 player has played 3 hours
1/31/2017 player did not log in
1/30/2017 player played 5 minutes
1/29/2017 player joined the server

-------------now for the ranks part (the part I am more interested in)------------

So, probably more than one way to do it but currently I am thinking this:

`Dedicated:
    requirements:
        money:
          value: 1000
        activity:
          increment: 24 #in hours, this is the segment of time we are looking at. If you put 24, then we are looking at how much activity in a given 24 hour period.
          amount: 1 #the requirement of hours in the given increment.
          type: recent #this option is just to add more functionality. "recent" is looking at the most recent segment (so in the last 24 hours in this case) Another option could be  "minimum" which would look at maybe the player had to play 1 hour every day ever. You could also implement an "average" option...but I hardly see it worth trying to implement because it could be complicated to config. I only am looking for the "recent" capability and don't really care if you implement this "type:" option. 
          options:
              derankable: true
              commands on derank:
              - say &p has just deranked!


`

**Comment by Staartvin** [comment]
Thanks for the feedback, see what I can do!

**Comment by mickcoyne** [comment]
No problem, thanks for considering this feature!

**Comment by Artige** [comment]
I would love something like this!

What I'm looking for is for the ability to rank people up along two paths. One is for seniority (total time invested) and the other would be player activity (how often they play on the server in a given month).

The idea behind this is that players who are more active would move up this path and less active ones would move down. This helps me get a better sense of the number of truly active players and lets me reward for being active!

This timeframe could adhere to the day/week/month just like the leaderboards so it would be simpler.

**Comment by Staartvin** [comment]
I've worked on the activity part. Can you install this dev version (http://178.62.255.148:8080/job/Autorank/49/) and try /ar activity <player> <time>?

**Comment by mickcoyne** [comment]
I am very sorry for the late reply. Midterms suck :P. Anyways, just test /ar activity and it is awesome.  Although I would probably change the wording on the command format. You have "Invalid format, use /ar activity <player> <history>" I would change it to "Invalid format, use /ar activity <player> <time>" People who use prism would understand that better imo. Alternatively, "Invalid format, use /ar activity <player> <since>"  which is actually an alternate for time in prism :P
