### ISSUE TITLE
Change behavior of /ar check command.

### ISSUE THREAD

**Issue by TheIntelloBox** [Staartvin/Autorank-2#504]
Hello.

With the version 3.5 of AutoRank, it was very easy to do /ar check : it told us when is the next rank, etc.
But with the new version you have to do /ar view reqs Rank ... It's very hard for my players.

So could you do the same system as the old version ?

Thanks !

**Comment by AntZaro** [comment]
Please do something about this command! I also liked the simplicity of /ar check before. I just updated to the most recent beta from version 3, and I find it really confusing to see all those messages when I do /ar check. 

On our server, donors don't have any autorank ranks available, but they would use /ar check to see how much time they've played. Now, they instead get this long message about viewing and choosing paths, none of which apply to them. It's just really confusing. Can there be an option to just display time played when someone does /ar check with no paths available to them? That would be so nice! Thank you.

Note: For those with ranks available by time (linear), /ar check works fine (albeit with more text) because I used the auto choose option in the config. It's only for those with no paths that it is the issue.

**Comment by TheIntelloBox** [comment]
Ant Zaro, yes it was better before ! :D

**Comment by Staartvin** [comment]
I changed the behavior so that requirements are assigned to a player by default (https://github.com/Staartvin/Autorank-2/commit/c4cb995db516e2ea1b521482270b0749ab5a6d3e#diff-500596436787bbd5d0bf4da18580a2e9R437) Does this change the behavior in a good way?

**Comment by TheIntelloBox** [comment]
Could you do like the old system ?

**Comment by AntZaro** [comment]
Yes, it's nice that they're assigned automatically, but for me the problem was what the /ar check command yields in chat now. 

Before this update, players would run /ar check and then see that they've played for X amount of time and whether or not there's a rank up available for them. Nice and simple. No confusion, and players could see their playtime. 

Now, players see this long amount of text in their chat talking about choosing paths and all this other stuff. All I wanted is a way to turn that off or change that. Players are confused by this, mostly the ones who are donors and don't have rankups available to them. They just want to see their total playtime like they did when they ran this command beforehand. Does that make sense?

**Comment by Staartvin** [comment]
@AntZaro This update should fix that.

**Comment by TheIntelloBox** [comment]
The old system is better : when you did /ar check you could see the time of game and the next rank.

**Comment by AntZaro** [comment]
All right. I'll give it a try and see. Thank you

**Comment by AntZaro** [comment]
I'm not sure that it's functioning the old way yet. 
![screen shot 2017-05-29 at 21 37 58](https://cloud.githubusercontent.com/assets/17606915/26565190/1ac8b8a2-44b7-11e7-987c-25fff572d2b3.png)

**Comment by AntZaro** [comment]
I checked a player who has no more paths available to them (they happen to be a donor, but this could happen for others with special ranks or staff). Before, this person would see a message saying they have no rankups available, and it would tell them their total time played. Now they're getting this message, which confuses many people. They ask me when the command will be "fixed"

**Comment by TheIntelloBox** [comment]
My players too. :)
