### ISSUE TITLE
AutoRank Removes other ranks on promotion

### ISSUE THREAD

**Issue by skylarcoolya** [Staartvin/Autorank-2#595]
So basically when someone ranks up it removes their staff rank I have it so their staff rank sets a suffix while the rank that gets ranked up gets a prefix but the staff rank is completely removed any possible fix or maybe a option to add the additional rank not remove all others

**Comment by Staartvin** [comment]
What permissions plugin do you use?

**Comment by skylarcoolya** [comment]
PermissionsEx

**Comment by TheIntelloBox** [comment]
I have the same problem with GroupManager.

You should add something like : "If player has Group "Staff", he isn't moved".

**Comment by skylarcoolya** [comment]
@TheIntelloBox that isn't what I am going for, it shouldn't remove ranks that are already there it should only add on to the current ranks

**Comment by TheIntelloBox** [comment]
So @Staartvin will you fix it ?

**Comment by TigerTBN** [comment]
@skylarcoolya This is not a problem from the AutoRank plugin. and the author has nothing to do with this.
It's my pleasure to help you out. Even if it was old but some people might see it and get the advantage.

The problem is for sure the command you entered for the plugin to execute when the player gets promoted.

Pretty much PermissionEX has 3 kinds of promotion commands:

- `/pex promote (name) (ladder)` This is when you have rank-ladder option in PEX permissions config. it will add the player to the next rank.  

- `/pex user (name) group set (group name)` It will remove the player from any other rank and give him the rank you entered in the command.

- `/pex user (name) group add (group name)` It will add the player to the rank you entered in the command and NOT remove him from any other ranks.

And this is pretty much it. If you can't see the issue yet, let me explain.

You might have entered in the paths.yml file that when the player gets promoted he will get his group `set` to the next rank.
So just change,
- `/pex user (name) group set (group name)`
to
- `/pex user (name) group add (group name)`

If this is not the issue please Message me or contact me on discord,

T Y L E R#6343

**Comment by skylarcoolya** [comment]
The above is correct I actually fixed this after I realized it wasn’t the plugin doing this it was customNPC’s doing this at spawn because we have a different npc per race and the person that set them up used set instead of add I believe can’t quite remember as this was months ago
