### ISSUE TITLE
"Not in group" prerequisite

### ISSUE THREAD

**Issue by SpaicyGaming** [Staartvin/Autorank-2#652]
Is there a "not in group" prerequisite? I can't find it in the wiki.
Here's what I'd like to do:
```
userplus:
    prerequisites:
        in group:
            value: user
        not in group:
            value: userplus
    requirements:
        # etc.
    results:
        # ...
```

I need to prevent players from joining a path if they already have that group. That's because there are other ways to get that group than autorank.

**Comment by Staartvin** [comment]
There is non yet, but I can look into adding that.

**Comment by SpaicyGaming** [comment]
Thank you!

**Comment by BijuuKrunos** [comment]
You can do this with a workaround. I think it should work if you give the group on which it should work a new permission like "test.test" and on the group where it shouldn't work the same permission but you have to set it as false. the "not" group need to have a higher prioritie!

Now you ask in ar for this permission:

permission:
  value: test.test

If he is in the group user. he has the Permission and can use this path.
But if he is in the group userplus as well. he can't use this path because his Priority is higher and he don't have the Permission anymore.


I hope you can understand what i mean xD. If not let me now!

Greetz 

Krunos
