### ISSUE TITLE
How to use "Player needs to have x advancements"?

### ISSUE THREAD

**Issue by leejosepho** [Staartvin/Autorank-2#661]
"Player needs to have x advancements" (amount xx) is part of 'Statz requirements' here:
https://github.com/Staartvin/Autorank-2/wiki/Requirements-&-Results#statz-requirements

I have spent a few hours trying everything I can think of to make use of the above, but I cannot figure out how to properly add multiple (two) advancements:
------
  requirements:
    time:
      value: 3h
    has advancement:
      amount: 2
        minecraft:story/mine_stone;Stone Age
        minecraft:story/smelt_iron;Acquire Hardware
------

Many thanks for any suggestions!

**Comment by BijuuKrunos** [comment]
I know this could be a little late but you should use it like this:
has advancement:
  value: "minecraft:story/mine_stone;Stone Age"
has advancement 2:
  value: "minecraft:story/smelt_iron;Acquire Hardware"


If you want to use the amount type it looks like that:

has advancement:
  value: 2

But the amount type is bad because it checks every advancement. Even the recipes.
