### ISSUE TITLE
Paths.yml not following prequisites

### ISSUE THREAD

**Issue by Rand404** [Staartvin/Autorank-2#669]
Hello, it appears that paths.yml is not following the 'prequisites' of a path.

This, in effect, means my donators are being demoted to the normal time-based rank, despite the prequisite specifying that they must be a certain rank to do so. Donators have all parent groups revoked so they have no association with their old rank and should not be getting their rank altered by autorank.

Paths.yml here:  https://pastebin.com/jeNAsm6z
Copy of debug file: https://pastebin.com/6Ua59ca9

**Comment by Issemir** [comment]
I had this issue to and had to give donors the timeexclude node to stop them being ranked up, however this is still problematic as I want them to be able to see their time played and request the permissions from each autorank level in the default path to be added to their permissions manually by staff. Essentially, the addition of a permission node along the lines of autorank.pathexclude would be nice? Something that allows their time to still be counted but exludes them from any rankup paths, and maybe the added feature of autorank.pathexclude.(path) so that it is further customisable and you can exclude them only from certain paths.
